"""
colleges.py — NBA player college/origin data.
"No college" = entered NBA directly from high school or international.
"""

PLAYER_COLLEGES = {
    # OKC Thunder
    "Shai Gilgeous-Alexander": "Kentucky",
    "Jalen Williams":           "Santa Clara",
    "Chet Holmgren":            "Gonzaga",
    "Isaiah Hartenstein":       "No college",
    "Luguentz Dort":            "Arizona State",
    "Alex Caruso":              "Texas A&M",
    "Cason Wallace":            "Kentucky",
    "Jared McCain":             "Duke",
    "Aaron Wiggins":            "Maryland",
    "Ajay Mitchell":            "Santa Barbara",

    # New York Knicks
    "Jalen Brunson":            "Villanova",
    "Karl-Anthony Towns":       "Kentucky",
    "OG Anunoby":              "Indiana",
    "Mikal Bridges":           "Villanova",
    "Josh Hart":               "Villanova",
    "Jose Alvarado":           "Georgia Tech",
    "Miles McBride":           "West Virginia",
    "Pacome Dadiet":           "No college",
    "Tyler Kolek":             "Marquette",
    "Guerschon Yabusele":      "No college",
    "Mitchell Robinson":       "No college",
    "Jordan Clarkson":         "Missouri",

    # Los Angeles Lakers
    "Luka Dončić":             "No college",
    "LeBron James":            "No college",
    "Austin Reaves":           "Arkansas",
    "Rui Hachimura":           "Gonzaga",
    "Dorian Finney-Smith":     "Florida",
    "Mark Williams":           "Duke",
    "Luke Kennard":            "Duke",
    "Dalton Knecht":           "Tennessee",
    "Gabe Vincent":            "UC Santa Barbara",
    "Maxi Kleber":             "No college",
    "Jaxson Hayes":            "Texas",
    "Bronny James":            "USC",

    # Cleveland Cavaliers
    "Donovan Mitchell":        "Louisville",
    "Evan Mobley":             "USC",
    "James Harden":            "Arizona State",
    "Jarrett Allen":           "Texas",
    "De'Andre Hunter":         "Virginia",
    "Max Strus":               "Lewis",
    "Lonzo Ball":              "UCLA",
    "Dean Wade":               "Kansas State",
    "Larry Nance Jr.":         "Wyoming",
    "Craig Porter Jr.":        "Wichita State",
    "Sam Merrill":             "Utah State",
    "Jaylon Tyson":            "Texas",

    # Denver Nuggets
    "Nikola Jokić":            "No college",
    "Jamal Murray":            "Kentucky",
    "Cameron Johnson":         "North Carolina",
    "Aaron Gordon":            "Arizona",
    "Michael Porter Jr.":      "Missouri",
    "Christian Braun":         "Kansas",
    "Russell Westbrook":       "UCLA",
    "Julian Strawther":        "Gonzaga",
    "Peyton Watson":           "UCLA",
    "DaRon Holmes II":         "Washington",
    "Zeke Nnaji":              "Arizona",
    "Jonas Valančiūnas":       "No college",

    # Dallas Mavericks
    "Kyrie Irving":            "Duke",
    "Cooper Flagg":            "Duke",
    "Klay Thompson":           "Washington State",
    "Khris Middleton":         "Texas A&M",
    "Daniel Gafford":          "Arkansas",
    "Dereck Lively II":        "Duke",
    "Caleb Martin":            "UNLV",
    "Naji Marshall":           "Xavier",
    "Tyus Jones":              "Duke",
    "Max Christie":            "Michigan State",
    "Dwight Powell":           "Stanford",
    "P.J. Washington":         "Kentucky",

    # Houston Rockets
    "Kevin Durant":            "Texas",
    "Alperen Sengun":          "No college",
    "Amen Thompson":           "No college",
    "Jalen Green":             "No college",
    "Dillon Brooks":           "Oregon",
    "Jabari Smith Jr.":        "Auburn",
    "Tari Eason":              "LSU",
    "Reed Sheppard":           "Kentucky",
    "Clint Capela":            "No college",
    "Steven Adams":            "No college",
    "Jeff Green":              "Georgetown",
    "Jae'Sean Tate":           "Ohio State",
    "Josh Okogie":             "Georgia Tech",

    # Indiana Pacers
    "Tyrese Haliburton":       "Iowa State",
    "Pascal Siakam":           "No college",
    "Ivica Zubac":             "No college",
    "Andrew Nembhard":         "Gonzaga",
    "Aaron Nesmith":           "Vanderbilt",
    "Bennedict Mathurin":      "Arizona",
    "Obi Toppin":              "Dayton",
    "Ben Sheppard":            "Bellarmine",
    "Jarace Walker":           "Houston",
    "Johnny Furphy":           "No college",
    "Jay Huff":                "Virginia",
    "T.J. McConnell":          "Arizona",
    "Kobe Brown":              "Missouri",

    # Minnesota Timberwolves
    "Anthony Edwards":         "Georgia",
    "Julius Randle":           "Kentucky",
    "Rudy Gobert":             "No college",
    "Jaden McDaniels":         "Washington",
    "Naz Reid":                "LSU",
    "Donte DiVincenzo":        "Villanova",
    "Ayo Dosunmu":             "Illinois",
    "Nickeil Alexander-Walker":"Virginia Tech",
    "Mike Conley":             "Ohio State",
    "Jaylen Clark":            "UCLA",
    "Joe Ingles":              "No college",
    "Gary Trent Jr.":          "Duke",
    "Terrence Shannon Jr.":    "Illinois",

    # Boston Celtics
    "Jayson Tatum":            "Duke",
    "Jaylen Brown":            "California",
    "Derrick White":           "Colorado",
    "Anfernee Simons":         "No college",
    "Nikola Vučević":          "No college",
    "Jrue Holiday":            "UCLA",
    "Payton Pritchard":        "Oregon",
    "Al Horford":              "Florida",
    "Sam Hauser":              "Virginia",
    "Xavier Tillman":          "Michigan State",
    "Jordan Walsh":            "Arkansas",
    "Baylor Scheierman":       "Creighton",
    "Neemias Queta":           "Utah State",

    # Atlanta Hawks
    "Dyson Daniels":           "No college",
    "Jalen Johnson":           "Duke",
    "Onyeka Okongwu":          "USC",
    "Jonathan Kuminga":        "No college",
    "Buddy Hield":             "Oklahoma",
    "Grant Williams":          "Tennessee",
    "Zaccharie Risacher":      "No college",
    "Asa Newell":              "No college",
    "Vít Krejčí":             "No college",
    "Mouhamed Gueye":          "No college",
    "Nikola Đurišić":          "No college",

    # San Antonio Spurs
    "Victor Wembanyama":       "No college",
    "De'Aaron Fox":            "Kentucky",
    "Stephon Castle":          "Connecticut",
    "Dylan Harper":            "Rutgers",
    "Devin Vassell":           "Florida State",
    "Keldon Johnson":          "Kentucky",
    "Jeremy Sochan":           "Baylor",
    "Harrison Barnes":         "North Carolina",
    "Julian Champagnie":       "St. John's",
    "Kelly Olynyk":            "Gonzaga",
    "Bismack Biyombo":         "No college",
    "Carter Bryant":           "Arizona",
    "Garrett Temple":          "LSU",

    # Golden State Warriors
    "Stephen Curry":           "Davidson",
    "Jimmy Butler III":        "Marquette",
    "Kristaps Porziņģis":      "No college",
    "Draymond Green":          "Michigan State",
    "Andrew Wiggins":          "Kansas",
    "Brandin Podziemski":      "Santa Clara",
    "Moses Moody":             "Arkansas",
    "Gary Payton II":          "Oregon State",
    "Trayce Jackson-Davis":    "Indiana",
    "De'Anthony Melton":       "USC",
    "Quinten Post":            "No college",
    "Will Richard":            "Florida",

    # Orlando Magic
    "Paolo Banchero":          "Duke",
    "Franz Wagner":            "Michigan",
    "Desmond Bane":            "TCU",
    "Jalen Suggs":             "Gonzaga",
    "Wendell Carter Jr.":      "Duke",
    "Jonathan Isaac":          "Florida State",
    "Anthony Black":           "Arkansas",
    "Tyus Jones":              "Duke",
    "Goga Bitadze":            "No college",
    "Tristan da Silva":        "Colorado",
    "Jase Richardson":         "Michigan State",
    "Noah Penda":              "No college",
    "Jett Howard":             "Michigan",

    # Philadelphia 76ers
    "Joel Embiid":             "Kansas",
    "Tyrese Maxey":            "Kentucky",
    "Paul George":             "Fresno State",
    "Kelly Oubre Jr.":         "Kansas",
    "Guerschon Yabusele":      "No college",
    "Andre Drummond":          "Connecticut",
    "Kyle Lowry":              "Villanova",
    "Eric Gordon":             "Indiana",
    "Adem Bona":               "UCLA",
    "Paul Reed":               "DePaul",
    "VJ Edgecombe":            "Baylor",
    "Justin Edwards":          "Kentucky",
    "Johni Broome":            "Auburn",
    "Trendon Watford":         "LSU",

    # Portland Trail Blazers
    "Damian Lillard":          "Weber State",
    "Jrue Holiday":            "UCLA",
    "Deni Avdija":             "No college",
    "Shaedon Sharpe":          "Kentucky",
    "Toumani Camara":          "Dayton",
    "Scoot Henderson":         "No college",
    "Deandre Ayton":           "Arizona",
    "Donovan Clingan":         "Connecticut",
    "Jerami Grant":            "Syracuse",
    "Kris Murray":             "Iowa",
    "Matisse Thybulle":        "Washington",
    "Robert Williams III":     "Texas A&M",
    "Rayan Rupert":            "No college",
    "Duop Reath":              "LSU",

    # Memphis Grizzlies
    "Ja Morant":               "Murray State",
    "Marcus Smart":            "Oklahoma State",
    "Kentavious Caldwell-Pope":"Georgia",
    "Santi Aldama":            "Loyola Maryland",
    "GG Jackson":              "South Carolina",
    "Zach Edey":               "Purdue",
    "Scotty Pippen Jr.":       "Vanderbilt",
    "Brandon Clarke":          "Gonzaga",
    "Vince Williams Jr.":      "VCU",
    "Cam Spencer":             "Connecticut",
    "Jaylen Wells":            "Washington State",
    "Ty Jerome":               "Virginia",
    "Jock Landale":            "No college",
    "Luke Kennard":            "Duke",

    # New Orleans Pelicans
    "Zion Williamson":         "Duke",
    "Trey Murphy III":         "Virginia",
    "Dejounte Murray":         "Washington",
    "Herbert Jones":           "Alabama",
    "Jordan Poole":            "Michigan",
    "Yves Missi":              "Connecticut",
    "Jordan Hawkins":          "Connecticut",
    "Jeremiah Fears":          "Oklahoma",
    "Micah Peavy":             "TCU",
    "Saddiq Bey":              "Villanova",
    "Derik Queen":             "Maryland",
    "Jaden Springer":          "Tennessee",
    "Karlo Matkovic":          "No college",

    # Sacramento Kings
    "Domantas Sabonis":        "Gonzaga",
    "DeMar DeRozan":           "USC",
    "Zach LaVine":             "UCLA",
    "Cam Whitmore":            "Villanova",
    "Malik Monk":              "Kentucky",
    "Dennis Schröder":         "No college",
    "Devin Carter":            "Providence",
    "Keon Ellis":              "Alabama",
    "Dario Šarić":             "No college",
    "Doug McDermott":          "Creighton",
    "Drew Eubanks":            "Oregon State",
    "Maxime Raynaud":          "Stanford",
    "Nique Clifford":          "Colorado State",
    "Corey Kispert":           "Gonzaga",

    # Miami Heat
    "Bam Adebayo":             "Kentucky",
    "Tyler Herro":             "Kentucky",
    "Andrew Wiggins":          "Kansas",
    "Norman Powell":           "UCLA",
    "Terry Rozier":            "Louisville",
    "Nikola Jović":            "No college",
    "Duncan Robinson":         "Williams College",
    "Jaime Jaquez Jr.":        "UCLA",
    "Kel'el Ware":             "Indiana",
    "Kyle Kuzma":              "Utah",
    "Simone Fontecchio":       "No college",
    "Kasparas Jakučionis":     "No college",
    "Davion Mitchell":         "Baylor",
    "Dru Smith":               "Missouri",

    # Milwaukee Bucks
    "Giannis Antetokounmpo":   "No college",
    "Damian Lillard":          "Weber State",
    "Bobby Portis":            "Arkansas",
    "Brook Lopez":             "Stanford",
    "Myles Turner":            "Texas",
    "Cole Anthony":            "North Carolina",
    "Kevin Porter Jr.":        "USC",
    "AJ Green":                "Wisconsin-Green Bay",
    "Taurean Prince":          "Baylor",
    "Gary Harris":             "Michigan State",
    "Andre Jackson Jr.":       "Connecticut",
    "Ryan Rollins":            "Toledo",
    "Amir Coffey":             "Minnesota",

    # Detroit Pistons
    "Cade Cunningham":         "Oklahoma State",
    "Jalen Duren":             "Memphis",
    "Ausar Thompson":          "No college",
    "Isaiah Stewart":          "Washington",
    "Tobias Harris":           "Tennessee",
    "Jaden Ivey":              "Purdue",
    "Caris LeVert":            "Michigan",
    "Tim Hardaway Jr.":        "Michigan",
    "Ronald Holland II":       "No college",
    "Gui Santos":              "No college",
    "Marcus Sasser":           "Houston",
    "Bobi Klintman":           "No college",
    "Chaz Lanier":             "North Florida",
    "Paul Reed":               "DePaul",

    # Toronto Raptors
    "Scottie Barnes":          "Florida State",
    "Brandon Ingram":          "Duke",
    "Immanuel Quickley":       "Kentucky",
    "RJ Barrett":              "Duke",
    "Jakob Poeltl":            "Utah",
    "Kelly Olynyk":            "Gonzaga",
    "Gradey Dick":             "Kansas",
    "Ochai Agbaji":            "Kansas",
    "Sandro Mamukelashvili":   "No college",
    "Jonathan Mogbo":          "San Francisco",
    "Collin Murray-Boyles":    "South Carolina",
    "Jamison Battle":          "Ohio State",
    "Jamal Shead":             "Houston",
    "Ja'Kobe Walter":          "Baylor",

    # Phoenix Suns
    "Kevin Durant":            "Texas",
    "Devin Booker":            "Kentucky",
    "Bradley Beal":            "Florida",
    "Grayson Allen":           "Duke",
    "Jusuf Nurkić":            "No college",
    "Dillon Brooks":           "Oregon",
    "Nick Richards":           "Kentucky",
    "Ryan Dunn":               "Virginia",
    "Royce O'Neale":           "Baylor",
    "Jordan Goodwin":          "Saint Louis",
    "Khaman Maluach":          "Duke",
    "Nigel Hayes-Davis":       "Wisconsin",
    "Rasheer Fleming":         "Saint Joseph's",
    "Collin Gillespie":        "Villanova",

    # Charlotte Hornets
    "LaMelo Ball":             "No college",
    "Brandon Miller":          "Alabama",
    "Miles Bridges":           "Michigan State",
    "Tidjane Salaün":          "No college",
    "Kon Knueppel":            "Duke",
    "Liam McNeeley":           "Connecticut",
    "Moussa Diabaté":          "Michigan",
    "Josh Green":              "Arizona",
    "Tre Mann":                "Florida",
    "Collin Sexton":           "Alabama",
    "Sion James":              "Duke",
    "Mason Plumlee":           "Duke",
    "Ryan Kalkbrenner":        "Creighton",

    # Utah Jazz
    "Jaren Jackson Jr.":       "Michigan State",
    "Lauri Markkanen":         "Arizona",
    "John Collins":            "Wake Forest",
    "Walker Kessler":          "Auburn",
    "Keyonte George":          "Baylor",
    "Taylor Hendricks":        "UCF",
    "Ace Bailey":              "Rutgers",
    "Cody Williams":           "Colorado",
    "Isaiah Collier":          "USC",
    "Kyle Filipowski":         "Duke",
    "Brice Sensabaugh":        "Ohio State",
    "Kyle Anderson":           "UCLA",
    "Kevin Love":              "UCLA",
    "Walter Clayton Jr.":      "Florida",

    # Chicago Bulls
    "Coby White":              "North Carolina",
    "Josh Giddey":             "No college",
    "Anfernee Simons":         "No college",
    "Patrick Williams":        "Florida State",
    "Matas Buzelis":           "No college",
    "Noa Essengue":            "No college",
    "Rob Dillingham":          "Kentucky",
    "Leonard Miller":          "No college",
    "Ayo Dosunmu":             "Illinois",
    "Jalen Smith":             "Maryland",
    "Isaac Okoro":             "Auburn",
    "Dalen Terry":             "Arizona",
    "Julian Phillips":         "Tennessee",

    # Washington Wizards
    "Anthony Davis":           "Kentucky",
    "Trae Young":              "Oklahoma",
    "Alex Sarr":               "No college",
    "Bilal Coulibaly":         "No college",
    "Jordan Poole":            "Michigan",
    "Khris Middleton":         "Texas A&M",
    "Malaki Branham":          "Ohio State",
    "Corey Kispert":           "Gonzaga",
    "AJ Johnson":              "Arkansas",
    "Kyshawn George":          "Miami (FL)",
    "Marvin Bagley III":       "Duke",
    "Bub Carrington":          "Pittsburgh",
    "Tre Johnson":             "Texas",
    "Anthony Gill":            "Virginia",

    # Brooklyn Nets
    "Cam Thomas":              "LSU",
    "Nic Claxton":             "Georgia",
    "Dennis Schröder":         "No college",
    "Noah Clowney":            "Alabama",
    "Trendon Watford":         "LSU",
    "Ben Simmons":             "LSU",
    "Ziaire Williams":         "Stanford",
    "Day'Ron Sharpe":          "North Carolina",
    "Jalen Wilson":            "Kansas",
    "Egor Demin":              "No college",
    "Nolan Traore":            "No college",
    "Terance Mann":            "Florida State",
    "Ben Saraf":               "No college",

    # Los Angeles Clippers
    "Kawhi Leonard":           "San Diego State",
    "Darius Garland":          "Vanderbilt",
    "Norman Powell":           "UCLA",
    "Bogdan Bogdanović":       "No college",
    "Bradley Beal":            "Florida",
    "Kobe Brown":              "Missouri",
    "Isaiah Jackson":          "Kentucky",
    "Kris Dunn":               "Providence",
    "James Wiseman":           "Memphis",
    "Derrick Jones Jr.":       "UNLV",
    "Nicolas Batum":           "No college",
    "John Collins":            "Wake Forest",
    "Jarace Walker":           "Houston",
}


def get_college(player_name: str) -> str:
    return PLAYER_COLLEGES.get(player_name, "N/A")
